// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: order/v1/order.proto

package order_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_STATUS_UNKNOWN_UNSPECIFIED Status = 0
	Status_STATUS_PENDING_PAYMENT     Status = 1
	Status_STATUS_PAID                Status = 2
	Status_STATUS_CANCELLED           Status = 3
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNKNOWN_UNSPECIFIED",
		1: "STATUS_PENDING_PAYMENT",
		2: "STATUS_PAID",
		3: "STATUS_CANCELLED",
	}
	Status_value = map[string]int32{
		"STATUS_UNKNOWN_UNSPECIFIED": 0,
		"STATUS_PENDING_PAYMENT":     1,
		"STATUS_PAID":                2,
		"STATUS_CANCELLED":           3,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_order_v1_order_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_order_v1_order_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{0}
}

type PaymentMethod int32

const (
	PaymentMethod_PAYMENT_METHOD_UNKNOWN_UNSPECIFIED PaymentMethod = 0
	PaymentMethod_PAYMENT_METHOD_CARD                PaymentMethod = 1
	PaymentMethod_PAYMENT_METHOD_SBP                 PaymentMethod = 2
	PaymentMethod_PAYMENT_METHOD_CREDIT_CARD         PaymentMethod = 3
	PaymentMethod_PAYMENT_METHOD_INVESTOR_MONEY      PaymentMethod = 4
)

// Enum value maps for PaymentMethod.
var (
	PaymentMethod_name = map[int32]string{
		0: "PAYMENT_METHOD_UNKNOWN_UNSPECIFIED",
		1: "PAYMENT_METHOD_CARD",
		2: "PAYMENT_METHOD_SBP",
		3: "PAYMENT_METHOD_CREDIT_CARD",
		4: "PAYMENT_METHOD_INVESTOR_MONEY",
	}
	PaymentMethod_value = map[string]int32{
		"PAYMENT_METHOD_UNKNOWN_UNSPECIFIED": 0,
		"PAYMENT_METHOD_CARD":                1,
		"PAYMENT_METHOD_SBP":                 2,
		"PAYMENT_METHOD_CREDIT_CARD":         3,
		"PAYMENT_METHOD_INVESTOR_MONEY":      4,
	}
)

func (x PaymentMethod) Enum() *PaymentMethod {
	p := new(PaymentMethod)
	*p = x
	return p
}

func (x PaymentMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_order_v1_order_proto_enumTypes[1].Descriptor()
}

func (PaymentMethod) Type() protoreflect.EnumType {
	return &file_order_v1_order_proto_enumTypes[1]
}

func (x PaymentMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentMethod.Descriptor instead.
func (PaymentMethod) EnumDescriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{1}
}

type Order struct {
	state           protoimpl.MessageState  `protogen:"open.v1"`
	OrderUuid       string                  `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	UserUuid        string                  `protobuf:"bytes,2,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	PartUuids       []string                `protobuf:"bytes,3,rep,name=part_uuids,json=partUuids,proto3" json:"part_uuids,omitempty"`
	TotalPrice      float64                 `protobuf:"fixed64,4,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	TransactionUuid *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=transaction_uuid,json=transactionUuid,proto3" json:"transaction_uuid,omitempty"`
	PaymentMethod   PaymentMethod           `protobuf:"varint,6,opt,name=payment_method,json=paymentMethod,proto3,enum=order.v1.PaymentMethod" json:"payment_method,omitempty"`
	Status          Status                  `protobuf:"varint,7,opt,name=status,proto3,enum=order.v1.Status" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *Order) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *Order) GetPartUuids() []string {
	if x != nil {
		return x.PartUuids
	}
	return nil
}

func (x *Order) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *Order) GetTransactionUuid() *wrapperspb.StringValue {
	if x != nil {
		return x.TransactionUuid
	}
	return nil
}

func (x *Order) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNKNOWN_UNSPECIFIED
}

func (x *Order) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNKNOWN_UNSPECIFIED
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserUuid      string                 `protobuf:"bytes,1,opt,name=user_uuid,json=userUuid,proto3" json:"user_uuid,omitempty"`
	PartUuids     []string               `protobuf:"bytes,2,rep,name=part_uuids,json=partUuids,proto3" json:"part_uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetUserUuid() string {
	if x != nil {
		return x.UserUuid
	}
	return ""
}

func (x *CreateRequest) GetPartUuids() []string {
	if x != nil {
		return x.PartUuids
	}
	return nil
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderUuid     string                 `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,2,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *CreateResponse) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

type PayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderUuid     string                 `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	PaymentMethod PaymentMethod          `protobuf:"varint,2,opt,name=payment_method,json=paymentMethod,proto3,enum=order.v1.PaymentMethod" json:"payment_method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PayRequest) Reset() {
	*x = PayRequest{}
	mi := &file_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayRequest) ProtoMessage() {}

func (x *PayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayRequest.ProtoReflect.Descriptor instead.
func (*PayRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *PayRequest) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

func (x *PayRequest) GetPaymentMethod() PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return PaymentMethod_PAYMENT_METHOD_UNKNOWN_UNSPECIFIED
}

type PayResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TransactionUuid string                 `protobuf:"bytes,1,opt,name=transaction_uuid,json=transactionUuid,proto3" json:"transaction_uuid,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PayResponse) Reset() {
	*x = PayResponse{}
	mi := &file_order_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayResponse) ProtoMessage() {}

func (x *PayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayResponse.ProtoReflect.Descriptor instead.
func (*PayResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *PayResponse) GetTransactionUuid() string {
	if x != nil {
		return x.TransactionUuid
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderUuid     string                 `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_order_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetRequest) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_order_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *GetResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type CancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderUuid     string                 `protobuf:"bytes,1,opt,name=order_uuid,json=orderUuid,proto3" json:"order_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_order_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_order_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *CancelRequest) GetOrderUuid() string {
	if x != nil {
		return x.OrderUuid
	}
	return ""
}

var File_order_v1_order_proto protoreflect.FileDescriptor

const file_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x14order/v1/order.proto\x12\border.v1\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\"\xb6\x02\n" +
	"\x05Order\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid\x12\x1b\n" +
	"\tuser_uuid\x18\x02 \x01(\tR\buserUuid\x12\x1d\n" +
	"\n" +
	"part_uuids\x18\x03 \x03(\tR\tpartUuids\x12\x1f\n" +
	"\vtotal_price\x18\x04 \x01(\x01R\n" +
	"totalPrice\x12G\n" +
	"\x10transaction_uuid\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x0ftransactionUuid\x12>\n" +
	"\x0epayment_method\x18\x06 \x01(\x0e2\x17.order.v1.PaymentMethodR\rpaymentMethod\x12(\n" +
	"\x06status\x18\a \x01(\x0e2\x10.order.v1.StatusR\x06status\"K\n" +
	"\rCreateRequest\x12\x1b\n" +
	"\tuser_uuid\x18\x01 \x01(\tR\buserUuid\x12\x1d\n" +
	"\n" +
	"part_uuids\x18\x02 \x03(\tR\tpartUuids\"P\n" +
	"\x0eCreateResponse\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid\x12\x1f\n" +
	"\vtotal_price\x18\x02 \x01(\x01R\n" +
	"totalPrice\"k\n" +
	"\n" +
	"PayRequest\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid\x12>\n" +
	"\x0epayment_method\x18\x02 \x01(\x0e2\x17.order.v1.PaymentMethodR\rpaymentMethod\"8\n" +
	"\vPayResponse\x12)\n" +
	"\x10transaction_uuid\x18\x01 \x01(\tR\x0ftransactionUuid\"+\n" +
	"\n" +
	"GetRequest\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid\"4\n" +
	"\vGetResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderR\x05order\".\n" +
	"\rCancelRequest\x12\x1d\n" +
	"\n" +
	"order_uuid\x18\x01 \x01(\tR\torderUuid*k\n" +
	"\x06Status\x12\x1e\n" +
	"\x1aSTATUS_UNKNOWN_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16STATUS_PENDING_PAYMENT\x10\x01\x12\x0f\n" +
	"\vSTATUS_PAID\x10\x02\x12\x14\n" +
	"\x10STATUS_CANCELLED\x10\x03*\xab\x01\n" +
	"\rPaymentMethod\x12&\n" +
	"\"PAYMENT_METHOD_UNKNOWN_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13PAYMENT_METHOD_CARD\x10\x01\x12\x16\n" +
	"\x12PAYMENT_METHOD_SBP\x10\x02\x12\x1e\n" +
	"\x1aPAYMENT_METHOD_CREDIT_CARD\x10\x03\x12!\n" +
	"\x1dPAYMENT_METHOD_INVESTOR_MONEY\x10\x042\x89\x03\n" +
	"\fOrderService\x12V\n" +
	"\x06Create\x12\x17.order.v1.CreateRequest\x1a\x18.order.v1.CreateResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/api/v1/orders\x12^\n" +
	"\x03Pay\x12\x14.order.v1.PayRequest\x1a\x15.order.v1.PayResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/api/v1/orders/{order_uuid}/pay\x12W\n" +
	"\x03Get\x12\x14.order.v1.GetRequest\x1a\x15.order.v1.GetResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/api/v1/orders/{order_uuid}\x12h\n" +
	"\x06Cancel\x12\x17.order.v1.CancelRequest\x1a\x16.google.protobuf.Empty\"-\x82\xd3\xe4\x93\x02':\x01*\"\"/api/v1/orders/{order_uuid}/cancelB>Z<github.com/A-mpol/Go-homework/shared/proto/order/v1;order_v1b\x06proto3"

var (
	file_order_v1_order_proto_rawDescOnce sync.Once
	file_order_v1_order_proto_rawDescData []byte
)

func file_order_v1_order_proto_rawDescGZIP() []byte {
	file_order_v1_order_proto_rawDescOnce.Do(func() {
		file_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)))
	})
	return file_order_v1_order_proto_rawDescData
}

var file_order_v1_order_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_order_v1_order_proto_goTypes = []any{
	(Status)(0),                    // 0: order.v1.Status
	(PaymentMethod)(0),             // 1: order.v1.PaymentMethod
	(*Order)(nil),                  // 2: order.v1.Order
	(*CreateRequest)(nil),          // 3: order.v1.CreateRequest
	(*CreateResponse)(nil),         // 4: order.v1.CreateResponse
	(*PayRequest)(nil),             // 5: order.v1.PayRequest
	(*PayResponse)(nil),            // 6: order.v1.PayResponse
	(*GetRequest)(nil),             // 7: order.v1.GetRequest
	(*GetResponse)(nil),            // 8: order.v1.GetResponse
	(*CancelRequest)(nil),          // 9: order.v1.CancelRequest
	(*wrapperspb.StringValue)(nil), // 10: google.protobuf.StringValue
	(*emptypb.Empty)(nil),          // 11: google.protobuf.Empty
}
var file_order_v1_order_proto_depIdxs = []int32{
	10, // 0: order.v1.Order.transaction_uuid:type_name -> google.protobuf.StringValue
	1,  // 1: order.v1.Order.payment_method:type_name -> order.v1.PaymentMethod
	0,  // 2: order.v1.Order.status:type_name -> order.v1.Status
	1,  // 3: order.v1.PayRequest.payment_method:type_name -> order.v1.PaymentMethod
	2,  // 4: order.v1.GetResponse.order:type_name -> order.v1.Order
	3,  // 5: order.v1.OrderService.Create:input_type -> order.v1.CreateRequest
	5,  // 6: order.v1.OrderService.Pay:input_type -> order.v1.PayRequest
	7,  // 7: order.v1.OrderService.Get:input_type -> order.v1.GetRequest
	9,  // 8: order.v1.OrderService.Cancel:input_type -> order.v1.CancelRequest
	4,  // 9: order.v1.OrderService.Create:output_type -> order.v1.CreateResponse
	6,  // 10: order.v1.OrderService.Pay:output_type -> order.v1.PayResponse
	8,  // 11: order.v1.OrderService.Get:output_type -> order.v1.GetResponse
	11, // 12: order.v1.OrderService.Cancel:output_type -> google.protobuf.Empty
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_order_v1_order_proto_init() }
func file_order_v1_order_proto_init() {
	if File_order_v1_order_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_v1_order_proto_rawDesc), len(file_order_v1_order_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_v1_order_proto_goTypes,
		DependencyIndexes: file_order_v1_order_proto_depIdxs,
		EnumInfos:         file_order_v1_order_proto_enumTypes,
		MessageInfos:      file_order_v1_order_proto_msgTypes,
	}.Build()
	File_order_v1_order_proto = out.File
	file_order_v1_order_proto_goTypes = nil
	file_order_v1_order_proto_depIdxs = nil
}
